import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import GeneralContext from "@/components/context/GeneralContext";
import { ModalContextProvider } from "@/components/context/ModalContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GeneralContext>
          <ModalContextProvider>{children}</ModalContextProvider>
        </GeneralContext>
      </body>
    </html>
  );
}
